### ISSUE TITLE
не работает сайт

### ISSUE THREAD

**Issue by sy2nyk** [leominov/datalock#1]
Здравствуйте! Что случилось с сайтом?

**Comment by leominov** [comment]
@sy2nyk привет, скинь ссылку целиком для проверки :)

**Comment by sy2nyk** [comment]
у меня вообще пишет что сайт заблокирован, я прописал ip, он работал, через неделю перестал уже. Может ip новый у Вас уже?

**Comment by leominov** [comment]
Попробуй http://vidach.ru

**Comment by sy2nyk** [comment]
спасибо большое!

**Comment by leominov** [comment]
Пожалуйста
