### ISSUE TITLE
Декодирование playlist

### ISSUE THREAD

**Issue by sy2nyk** [leominov/datalock#2]
Берем закодированную ссылку на файл вида:

`#2aHR0cDovL2RhdGExMS1jZG4uZGF0YWxvY2sucnUvZmkybG0vMC83Zl9XZXN0d29ybGQuW1M//b2xvbG8=wMUUwMV0uSEQ3MjAuRFVCLltxcXNzNDRdLmExLjAzLjEwLjE2Lm1wNA==`

Убираем 

`#2` и `//b2xvbG8=`, далее делаем `base64_decode` и получаем ссылку `http:/.../fi2lm/0/7f_Westworld.[S01E01].HD720.DUB.[qqss44].a1.03.10.16.mp4`

Пользуемся дальше HD качеством.

**Comment by leominov** [comment]
👍
